export { Nav } from "./Nav";
export { Header } from "./Header";
export { Footer } from "./Footer";
export { Divider } from "./Divider";
export { Slogans } from "./Slogans";
export { Features } from "./Features";
export { Pagination } from "./Pagination"
export { SloganForm } from "./SloganForm";
export { ProductCard } from "./ProductCard";
export { OtherProducts } from "./OtherProducts";